# data_config = {
# 	'reddit'            : 'reddit_refined.txt',
# 	'cornell'           : 'cornell_refined.txt',
# 	'twitter'           : 'twitter_refined.txt',
# 	'filtered'          : 'all_filtered.txt',
# 	'metadata'          : 'metadata.pkl',
# 	'freq_dist'         : 'freq_dist.pkl',
# 	'min_context'       : 1,
# 	'max_context'       : 20,
# 	'min_reply'         : 1,
# 	'max_reply'         : 20,
# 	'vocab_size'        : 20000,
# 	'pad'               : '<PAD>',
# 	'unk'               : '<UNK>',
# 	'go'                : '<GO>',
# 	'eos'               : '<EOS>',
# 	'segment_size'      : 250000,
# 	'segment_prefix'    : 'segment_',
# 	'offset_size'       : 20000,
# 	'context_prefix'    : 'context_',
# 	'reply_prefix'      : 'reply_',
# }

data_config = {
	'reddit'            : 'reddit_refined.txt',
	'cornell'           : 'cornell_refined.txt',
	'twitter'           : 'twitter_refined.txt',
	'filtered'          : 'all_filtered.txt',
	'checking'          : 'all_filtered_checking.txt',
	'metadata'          : 'metadata.pkl',
	'freq_dist'         : 'freq_dist.pkl',
	'min_context'       : 1,
	'max_context'       : 24,
	'min_reply'         : 1,
	'max_reply'         : 24,
	'vocab_size'        : 600,
	'pad'               : '<PAD>',
	'unk'               : '<UNK>',
	'go'                : '<GO>',
	'eos'               : '<EOS>',
	'segment_size'      : 250000,
	'segment_prefix'    : 'segment_',
	'offset_size'       : 20000,
	'context_prefix'    : 'context_',
	'reply_prefix'      : 'reply_',
	'max_allowed_per_step'   : 2000,
}
